[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
regtech = "24tGu1PF1WwazTDeW4VWaJnqnGK2S422ntkmX7vfA2aq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
